source /Users/kael/.ideavim/file.vim
source /Users/kael/.ideavim/buffer.vim
source /Users/kael/.ideavim/search.vim
source /Users/kael/.ideavim/goto.vim
source /Users/kael/.ideavim/git.vim
source /Users/kael/.ideavim/view.vim
source /Users/kael/.ideavim/open.vim
source /Users/kael/.ideavim/project.vim
source /Users/kael/.ideavim/delete.vim
