#!/bin/sh

## General Config
## Envs
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'
export AWT_TOOLKIT=MToolkit
export INPUT_METHOD="fcitx5"
export XMODIFIERS="@im=fcitx5"
export GTK_IM_MODULE="fcitx5"
export QT_IM_MODULE="fcitx5"
export SXHKD_SHELL=/usr/bin/bash

# Keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#908caa"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a TelegramDesktop desktop='^2'
#bspc rule -a Steam desktop='^3'
bspc rule -a Screenkey manage=off
bspc rule -a vlc state=floating
bspc rule -a mpv state=floating
bspc rule -a feh state=floating center=true
bspc rule -a imv state=floating center=true
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a utools focus=on

## Autostart
# Xrandr
#xrandr --output HDMI-A-0 --mode 1920x1080 --rate 75.00 --rotate normal --pos 0x0 &

setxkbmap -option -option caps:swapescape;
xset r rate 200 50;

# Fix Cursor
xsetroot -cursor_name left_ptr &

# Xresources
xrdb $HOME/.Xresources &

# Compositor
picom &

# Polybar
polybar &
#~/.config/polybar/launch &

# Notify Daemon
dunst &

# Eww
# [ -n "$(pidof eww)" ] || eww daemon && eww open bar &

# Fix eww above fullscreen windows
#fullscreen &
# fcitx5
[ -n "$(pidof fcitx5)" ] || fcitx5 &

# utools
[ -n "$(pidof utools)" ] || utools &

# flameshot
[ -n "$(pidof flameshot)" ] || flameshot &

# Xsettings
[ -n "$(pidof xsettingsd)" ] || xsettingsd &

# Polkit
[ -n "$(pidof polkit-gnome-authentication-agent-1)" ] ||
  /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Thunar daemon mode
[ -n "$(pidof thunar)" ] || thunar --daemon &

# lock
betterlockscreen -u ~/Pictures/wallpapers

# Wallpaper
$HOME/.config/bspwm/scripts/wp-autochange.sh &
